---
- name: restart django
  supervisorctl:
    name: django
    state: restarted
  become: yes

- name: restart nginx
  systemd:
    name: nginx
    state: restarted
  become: yes

- name: restart supervisor
  systemd:
    name: supervisor
    state: restarted
  become: yes