---
# Simple PostgreSQL setup without problematic modules
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600
  become: yes

- name: Install PostgreSQL and dependencies
  apt:
    name:
      - postgresql
      - postgresql-contrib
      - python3-psycopg2
    state: present
  become: yes

- name: Stop PostgreSQL service
  systemd:
    name: postgresql
    state: stopped
  become: yes
  ignore_errors: yes

- name: Kill any remaining PostgreSQL processes
  shell: |
    pkill -f postgres || true
    sleep 2
  become: yes
  ignore_errors: yes

- name: Remove any existing cluster
  shell: |
    pg_dropcluster --stop 14 main || true
  become: yes
  ignore_errors: yes

- name: Remove PostgreSQL configuration directory
  file:
    path: /etc/postgresql/14/main
    state: absent
  become: yes

- name: Remove PostgreSQL data directory
  file:
    path: /var/lib/postgresql/14/main
    state: absent
  become: yes

- name: Create fresh PostgreSQL cluster
  shell: |
    pg_createcluster 14 main
  become: yes

- name: Start PostgreSQL cluster
  shell: |
    pg_ctlcluster 14 main start
  become: yes

- name: Start and enable PostgreSQL service
  systemd:
    name: postgresql
    state: started
    enabled: yes
  become: yes

- name: Wait for PostgreSQL to be ready
  wait_for:
    port: 5432
    timeout: 60

- name: Debug PostgreSQL cluster status
  shell: |
    echo "=== PostgreSQL Cluster Status ==="
    pg_lsclusters
    echo "=== PostgreSQL Service Status ==="
    systemctl status postgresql || true
    echo "=== PostgreSQL Process Check ==="
    ps aux | grep postgres || true
  register: pg_debug
  become: yes

- name: Show PostgreSQL debug info
  debug:
    var: pg_debug.stdout_lines

- name: Create database user
  shell: |
    sudo -u postgres psql -c "SELECT 1 FROM pg_user WHERE usename = '{{ db_user }}'" | grep -q 1 || \
    sudo -u postgres psql -c "CREATE USER {{ db_user }} WITH PASSWORD '{{ db_password }}';"
  become: yes

- name: Create database
  shell: |
    sudo -u postgres psql -c "SELECT 1 FROM pg_database WHERE datname = '{{ db_name }}'" | grep -q 1 || \
    sudo -u postgres createdb -O {{ db_user }} {{ db_name }}
  become: yes

- name: Grant database privileges
  shell: |
    sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE {{ db_name }} TO {{ db_user }};"
  become: yes

- name: Configure PostgreSQL authentication
  template:
    src: pg_hba.conf.j2
    dest: /etc/postgresql/14/main/pg_hba.conf
    owner: postgres
    group: postgres
    mode: '0640'
    backup: yes
  become: yes
  notify: restart postgresql

- name: Configure PostgreSQL main settings
  template:
    src: postgresql.conf.j2
    dest: /etc/postgresql/14/main/postgresql.conf
    owner: postgres
    group: postgres
    mode: '0644'
    backup: yes
  become: yes
  notify: restart postgresql

- name: Create backup directory
  file:
    path: /var/backups/postgresql
    state: directory
    owner: postgres
    group: postgres
    mode: '0755'
  become: yes

- name: Configure log rotation for PostgreSQL
  template:
    src: postgresql.logrotate.j2
    dest: /etc/logrotate.d/postgresql
    owner: root
    group: root
    mode: '0644'
  become: yes