---
# Complete PostgreSQL reset and initialization
- name: Stop PostgreSQL service
  systemd:
    name: postgresql
    state: stopped
  become: yes
  ignore_errors: yes

- name: Kill any remaining PostgreSQL processes
  shell: |
    pkill -f postgres || true
  become: yes
  ignore_errors: yes

- name: Remove all PostgreSQL clusters
  shell: |
    pg_dropcluster --stop 14 main || true
  become: yes
  ignore_errors: yes

- name: Remove PostgreSQL data directory
  file:
    path: /var/lib/postgresql/14
    state: absent
  become: yes

- name: Remove PostgreSQL config directory
  file:
    path: /etc/postgresql/14
    state: absent
  become: yes

- name: Reinstall PostgreSQL to ensure clean state
  apt:
    name:
      - postgresql
      - postgresql-contrib
      - python3-psycopg2
    state: latest
    force: yes
  become: yes

- name: Create fresh PostgreSQL cluster
  shell: |
    pg_createcluster 14 main
  become: yes

- name: Start PostgreSQL cluster
  shell: |
    pg_ctlcluster 14 main start
  become: yes

- name: Enable and start PostgreSQL service
  systemd:
    name: postgresql
    state: started
    enabled: yes
  become: yes

- name: Wait for PostgreSQL to be ready
  wait_for:
    port: 5432
    timeout: 60